### ISSUE TITLE
Revisar generacion csv (versión alpha)

### ISSUE THREAD

**Issue by snchz** [snchz/QueryExport#1]
Tras las últimas modificaciones hay que revisar la generación del fichero csv:

> Leyendo parametros...
> Lanzando query...
> Extension CSV
> Escribiendo fichero...
> java.lang.Exception: Error al generar CSV File.csv
>         Detalles: Juego de resultados cerrado: getMetaData
>         at ExportadorQuery.EscribirCSV(ExportadorQuery.java:143)
>         at ExportadorQuery.Ejecutar(ExportadorQuery.java:45)
>         at Principal.main(Principal.java:16)
> HORA FIN 2015/09/02 08:28:23
> TIEMPO DE EJECUCIËN: 6*

**Comment by snchz** [comment]
El metodo debe retornar una matriz como la siguiente:

``` java
    private List<Map<String, Object>> ObtenerResulsetQuery() throws Exception {
        Statement stmt;
        Connection conn;
        String log = "";
        List<Map<String, Object>> resultList = new ArrayList<Map<String, Object>>();

        try {
            log = log + "[Paso 1 de 3]Buscando driver " + _driver + "...\n";
            Class.forName(_driver);
            log = log + "Driver " + _driver + " encontrado.\n";
            log = log + "[Paso 2 de 3]Realizando conexion " + _url + "...\n";
            conn = DriverManager.getConnection(_url, _user, _pass);
            log = log + "Conexion " + _url + " realizada.\n";
            stmt = conn.createStatement();
            log = log + "[Paso 3 de 3]Lanzando query...\n";
            ResultSet rs = stmt.executeQuery(_query);
            log = log + "Query obtenida.\n";


            Map<String, Object> row = null;

            ResultSetMetaData metaData = rs.getMetaData();
            Integer columnCount = metaData.getColumnCount();

            while (rs.next()) {
                row = new HashMap<String, Object>();
                for (int i = 1; i <= columnCount; i++) {
                    row.put(metaData.getColumnName(i), rs.getObject(i));
                }
                resultList.add(row);
            }
        } catch (SQLException | ClassNotFoundException e) {
            log = log + "ERROR!!!";
            throw new Exception("Error leer de la base de datos " + _fileOutput + "\n\tLog:\n" + log + "\n\tDetalles: "
                    + e.getMessage());
        } finally{
            if (rs != null)
                rs.close();
            if (stmt != null) 
                stmt.close();
            if (conn != null)
                conn.close();
        }
        return resultList;
    }
```

**Comment by snchz** [comment]
> Leyendo parametros...
> Lanzando query...
> java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.
> String;
>         at ExportadorQuery.ObtenerResulsetQuery(ExportadorQuery.java:206)
>         at ExportadorQuery.Ejecutar(ExportadorQuery.java:41)
>         at Principal.main(Principal.java:16)

La linea 206:

``` java
resultList.add((String[]) row.toArray());
```

Cambiar por:

``` java
resultList.add(row.toArray(new String[row.size()]));
```
